name: Build and deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: '18'
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: dist
            path: dist

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: dist
            path: dist

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mattiaeffendi/docker-test
          registry: docker.io
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
                  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: dist
            path: dist

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist

  aws-deploy:
    runs-on: ubuntu-latest
    needs: [build, dockerize]
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: 'eu-west-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: i-007cc70d3bb5a67fd

          working-directory: /root
          command: docker-compose pull && docker-compose up -d